# Generated by Django 4.2 on 2025-04-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAsteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo_reference_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('diameter_max_meters', models.FloatField()),
                ('is_potentially_hazardous', models.BooleanField()),
                ('close_approach_date', models.DateField()),
                ('miss_distance_km', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
