# Generated by Django 4.2 on 2025-04-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_explorer', '0002_cachedasteroid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('net', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('mission', models.CharField(blank=True, max_length=200, null=True)),
                ('rocket', models.CharField(max_length=200)),
                ('pad', models.CharField(max_length=200)),
                ('agency', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CachedMarsWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol', models.IntegerField(unique=True)),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('pressure', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
