# Generated by Django 4.2 on 2025-04-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_explorer', '0003_cachedlaunch_cachedmarsweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmarsweather',
            name='first_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedmarsweather',
            name='last_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedmarsweather',
            name='most_common_wind_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cachedmarsweather',
            name='temperature_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedmarsweather',
            name='temperature_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedmarsweather',
            name='wind_speed_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
