# Generated by Django 4.2 on 2025-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_explorer', '0004_cachedmarsweather_first_utc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apod',
            name='copyright',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apod',
            name='hdurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apod',
            name='media_type',
            field=models.CharField(default='image', max_length=20),
        ),
        migrations.AlterField(
            model_name='apod',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
